"""align orders for quote conversion

Revision ID: 9fabb98304c5
Revises: bf77cf248393
Create Date: 2026-04-08 14:44:21.268789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fabb98304c5'
down_revision: Union[str, Sequence[str], None] = 'bf77cf248393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quote_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=False))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'orders', ['quote_id'])
    op.create_foreign_key(None, 'orders', 'quotes', ['quote_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'quote_id')
    # ### end Alembic commands ###
