from app.models.product import Product
from app.models.user import User
from app.models.application_area import ApplicationArea
from app.models.product_application_area import ProductApplicationArea
from app.models.spare_part import SparePart
from app.models.order import Order
from app.models.order_item import OrderItem
from app.models.quote_request import QuoteRequest
from app.models.ai_analysis import AIAnalysis
